### ISSUE TITLE
what if requestURI is "https://www.example.com" in RequestParser.path() ?

### ISSUE THREAD

**Issue by kareanyi** [neowu/core-ng-project#13]
Hi, Neo
When I set "https://www.example.com" in requestURI , it will return "https://www.example.com" in RequestParser.path() .  Is it wright? Or in out project , this will not happen ?

`var exchange = new HttpServerExchange(null);`
`exchange.setRequestURI("https://www.example.com", true);`
`assertThat(parser.path(exchange)).isEqualTo("https://www.example.com");`

**Comment by kareanyi** [comment]
I think it should return "".

**Comment by neowu** [comment]
Hi, I assume you refer to version 6.9.6? 
the reason I impl parser.path() is due to undertow bug, and which is fixed in latest undertow
https://github.com/undertow-io/undertow/pull/678

so in current impl, i reverted back to disable DECODE_URL, and the path will be retrieved by 
```
RequestImpl
    @Override
    public String path() {
        return exchange.getRequestPath();
    }
```
have you encountered any issue?

**Comment by kareanyi** [comment]
I've pulled the code and see the changes.
Thank you for your reply~
