### ISSUE TITLE
Add support for org.bson.types.Binary type in Mongo Collection Entity Codec

### ISSUE THREAD

**Issue by tsingyee** [neowu/core-ng-project#2]
Hi @neowu , can you add support for org.bson.types.Binary in Mongo Collection Entity Codec?

**Comment by neowu** [comment]
Hi @tsingyee, I don't plan to add Binary support, here are the reasons
1) we don't plan to use Mongo to save large binary. s3 will do it.
2) for small binary, Base64 is recommended, because it's plain text, easier to read/copy thru terminal/text based tool
3) even for binary, the supported type should be byte[], but as you know core-ng force use Object type rather than primitive type, List<Byte> definitely bad idea, and add byte[] creates inconsistency.

anyway, for reason 1-3, it seems not support it benefits more.

you are free to fork core-ng and supported (should be straightforward) if you really need it.

let me know if you have any thought.

**Comment by tsingyee** [comment]
Thank you @neowu for the explanation.
