### ISSUE TITLE
can support command line Arguments?

### ISSUE THREAD

**Issue by nealxu-chancetop** [neowu/core-ng-project#20]
like spring boot sport ,  java -jar spring-5.jar --server.port=8083

can add like [sys.https.port] into vm option,   and replace exist [context.propertyManager.properties] key. we often use different port on each project. i think it will quick development.

**Comment by neowu** [comment]
If you check propertymanager , it supports to override by env or java vm arguments, if you want to start with java you can pass like -Dsys.http.port=8081

**Comment by nealxu-chancetop** [comment]
yes ~~ i find  PropertyManager support get key from env, 
but  if i don't config with xxx.properties, it will return a Optional.empty()... 
` if (!properties.containsKey(key)) return Optional.empty();`
i think, Can you do that add default config into PropertyManager.properties? like that, it will work and better extension  👋 
`HTTPServer :  if (httpPort == null && httpsPort == null) httpPort = 8080;    // by default start http`

**Comment by neowu** [comment]
it is intended behavior, the design goal of framework is to make review/refactor friendly, over saving some code ( explicitly/strictness over CoC/dynamic), which means we are targeting long term project (the time spent on maintenance/refactor is much more than initial development)

to make deployment/review friendly, we should say what properties are defined by checking property files, so you can't override one non-defined property, (vise versa, framework is also report error if you defined one property in property file but not using it),
the reason is that by reviewing module/property, we should be able to reason how app is constructed easily (deterministic over dynamic which is appreciated when you are on large scale of system)

and regarding to default httpPort,  for some built in services, we try to make default values for common (cloud based webapp in our case), like pool size, like kafka settings, 
I guess you want to start https without define sys.https.port? in that case if you service is always run https on both local and cloud, why not just define sys.https.port? which is more clear

**Comment by nealxu-chancetop** [comment]
Got it,  convention over configuration
but.. The actual usage scenario is multi projects don't config 'sys.http.port' properties
when we develop a project or test a controller, if exists multi third part web service invoked,we need run target project and add new port config( because target port don't config port,so it's run default 8080)

if test is passed, then begin gradle build, it's will conf() FAILED. because i increase a new properties,but don't add other environment. now  i need manually remove new increase config. then rebuild..
now we move modify properties file to git another changelist,but if we need modify, we need again move it. 😢 This is a little repetitive & tedious  operate.

That's why I suggested add 'httpPort' to default config, we can dynamic replace it. 
Or our project all specify ports in properties?

**Comment by neowu** [comment]
i see your case now, 

i think it's due to the team not defining sys.https.port when project is small, 
if you always need to start multiple services locally, 
i think best way is to put sys.https.port in sys.properties for all envs. 

there are multiple benefits,
1) the team can predefine local env ports, it's not only for sys.https.port, but also on client side, e.g. 
you can put website on 8443, customer service on 8444 and so on, 
app.customerURL=https://localhost:8444 (as example)
then you can start both website and customer-service locally to test end-to-end

2) it will make local dev easier, you don't even need to customize start arguments, but run main class out of box, it will help other engineers and new team members. 
to simplify everyone's local setup

Thanks,
Neo

**Comment by nealxu-chancetop** [comment]
got it~~  Thanks a lot  😃
